<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.automation.framework</groupId>
  <artifactId>com.automation.framework</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <name>TECHPANDA_MAVEN</name>
     <!-- Khai báo biến - Global Variable -->
    <properties>
        <!-- Encoding for Build/ Console -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Encoding for Report -->
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

   <!-- Compiler Code with Java 21 -->
        <maven.compiler.target>21</maven.compiler.target>
        <maven.compiler.source>21</maven.compiler.source>

        <!-- Global variable for dependencies -->
        <webdriver.version>4.25.0</webdriver.version>
        <testng.version>7.8.0</testng.version>
        <jackson.version>2.10.0</jackson.version>
        <aspectj.version>1.9.21</aspectj.version>
        <allure.version>2.24.0</allure.version>
        <extent.version>5.1.1</extent.version>
        <log4j.version>2.19.0</log4j.version>
        <reportng.version>1.1.4</reportng.version>
        <cucumberjava.version>7.14.0</cucumberjava.version>
        <cucumbertestng.version>7.14.0</cucumbertestng.version>

    </properties>

    <!-- Quản lí thư viện -->
    <dependencies>
    
        <!-- LOMBOK -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.30</version> 
            <scope>provided</scope>
        </dependency>
        
        <!-- REST ASSURED -->
        <dependency>
           <groupId>io.rest-assured</groupId>
           <artifactId>rest-assured</artifactId>
           <version>5.5.0</version>
        </dependency>

        <dependency>
            <groupId>org.jsoup</groupId>
            <artifactId>jsoup</artifactId>
            <version>1.17.2</version>
        </dependency>
        
        <!-- Thư viện tự động xuất Extent Report v5 cho Cucumber 7 -->
        <dependency>
            <groupId>tech.grasshopper</groupId>
            <artifactId>extentreports-cucumber7-adapter</artifactId>
            <version>1.14.0</version>
            <scope>test</scope>
        </dependency>

        <!-- PostgreSQL JDBC Driver - Giữ nguyên em này trong pom.xml nha anh -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <version>42.7.2</version>
        </dependency>
        
        <!-- TestNG -->
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>${testng.version}</version>
        </dependency>

        <!-- Selenium Java -->
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${webdriver.version}</version>
        </dependency>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-support</artifactId>
            <version>${webdriver.version}</version>
        </dependency>

        <dependency>
            <groupId>org.uncommons</groupId>
            <artifactId>reportng</artifactId>
            <version>${reportng.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>${jackson.version}</version>
        </dependency>

        <dependency>
            <groupId>com.aventstack</groupId>
            <artifactId>extentreports</artifactId>
            <version>${extent.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>${log4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>${log4j.version}</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.36</version>
        </dependency>
        
        <dependency>
           <groupId>org.slf4j</groupId>
           <artifactId>slf4j-simple</artifactId>
           <version>1.7.36</version>
      </dependency>

        <dependency>
            <groupId>velocity</groupId>
            <artifactId>velocity-dep</artifactId>
            <version>1.4</version>
        </dependency>

        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
            <version>4.1.0</version>
        </dependency>

        <dependency>
            <groupId>commons-logging</groupId>
            <artifactId>commons-logging</artifactId>
            <version>1.2</version>
        </dependency>
        
        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.11.0</version>
        </dependency>

        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-testng</artifactId>
            <version>${allure.version}</version>
        </dependency>

        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjweaver</artifactId>
            <version>${aspectj.version}</version>
            <scope>runtime</scope>
        </dependency>
        
        <!-- Cucumber -->
    <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-java</artifactId>
        <version>${cucumberjava.version}</version>
    </dependency>

    <dependency>
        <groupId>io.cucumber</groupId>
        <artifactId>cucumber-testng</artifactId>
        <version>${cucumbertestng.version}</version>
    </dependency>
    
    <dependency>
    <groupId>io.qameta.allure</groupId>
    <artifactId>allure-cucumber7-jvm</artifactId>
    <version>${allure.version}</version>
    </dependency>
    
    
    </dependencies>

    <!-- Compiler/ Run Test -->
    <build>
        <plugins>
            <!-- Compiler -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.10.1</version>
                <!-- Compiler code vs Java 21 -->
                <configuration>
                    <source>21</source>
                    <target>21</target>
                </configuration>
            </plugin>

            <!-- Run test -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.1.2</version>
                <configuration>
                    <!-- Run TestNG xml file 
                   <suiteXmlFiles>
                        <suiteXmlFile>src/test/resources/runTest.xml</suiteXmlFile>
                    </suiteXmlFiles>-->
                    <!-- Run Cucumber -->
                    <includes>
                    <include>**/TestRunner.java</include>
                   </includes>

                    <!-- Run Parallel -->
                    <properties>
                        <property>
                            <name>parallel</name>
                            <value>methods</value> <!-- Can also be 'classes' or 'both' depending on your setup -->
                        </property>
                        <property>
                            <name>dataproviderthreadcount</name>
                            <value>2</value> <!-- Set your desired thread count here -->
                        </property>
                    </properties>
                    <!-- Argument -->
                    <argLine>
                        -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                    </argLine>
                </configuration>


            </plugin>
        </plugins>
    </build>
</project>
